# 멀티 스테이징, gradle 기반의 build 이미지
FROM gradle:7.6.1-jdk17-alpine as build

ENV APP_HOME=/apps
WORKDIR $APP_HOME

# gradle로 프로젝트 의존성 설치
COPY build.gradle settings.gradle gradlew $APP_HOME/
RUN gradle build --parallel --continue > /dev/null 2>&1 || true

# Gradle 관련 설정 파일들을 컨테이너 내부로 복사
COPY gradle $APP_HOME/gradle
RUN chmod +x gradlew

# 소스 코드 복사
COPY src $APP_HOME/src

# 테스트 실행
RUN ./gradlew test

# jar 정리하고 빌드
RUN ./gradlew clean build


FROM openjdk:17-jdk-slim

ENV APP_HOME=/apps
ARG ARTIFACT_NAME=app.jar
ARG JAR_FILE_PATH=build/libs/Rememberall-1.0.jar

WORKDIR $APP_HOME

COPY --from=build $APP_HOME/$JAR_FILE_PATH $ARTIFACT_NAME

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]